//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppMusic
{
    using System;
    using System.Collections.Generic;
    
    public partial class SONG
    {
        public int idSong { get; set; }
        public string SongName { get; set; }
        public string Artist { get; set; }
        public System.TimeSpan TotalTime { get; set; }
        public string FilePath { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<int> idPlaylist { get; set; }
    
        public virtual PLAYLIST PLAYLIST { get; set; }
    }
}
